-- CREATE DATABASE aabeav1

--\c aabeav1

CREATE TABLE users(

id serial PRIMARY KEY,
username VARCHAR ( 255 ) UNIQUE NOT NULL,
email VARCHAR ( 255 ) UNIQUE NOT NULL,
password VARCHAR ( 255 ) NOT NULL,
isAdmin BOOLEAN NOT NULL,
createdAt TIMESTAMP NOT NULL,
updatedAt TIMESTAMP NOT NULL
)

-- CHECK CURRENT / LAST SEQUENCE
 SELECT * FROM "members_memberId_seq";
        -- CHANGE THE LAST VALUE
ALTER SEQUENCE "members_memberId_seq" RESTART WITH 1000;