export const CHAPTER_REGISTER_REQUEST = 'CHAPTER_REGISTER_REQUEST';
export const CHAPTER_REGISTER_SUCCESS = 'CHAPTER_REGISTER_SUCCESS';
export const CHAPTER_REGISTER_FAIL = 'CHAPTER_REGISTER_FAIL';
export const CHAPTER_REGISTER_RESET = 'CHAPTER_REGISTER_RESET';

export const CHAPTER_LIST_REQUEST = 'CHAPTER_LIST_REQUEST';
export const CHAPTER_LIST_SUCCESS = 'CHAPTER_LIST_SUCCESS';
export const CHAPTER_LIST_FAIL = 'CHAPTER_LIST_FAIL';
export const CHAPTER_LIST_RESET = 'CHAPTER_LIST_RESET';

export const CHAPTER_DETAILS_REQUEST = 'CHAPTER_DETAILS_REQUEST';
export const CHAPTER_DETAILS_SUCCESS = 'CHAPTER_DETAILS_SUCCESS';
export const CHAPTER_DETAILS_FAIL = 'CHAPTER_DETAILS_FAIL';
export const CHAPTER_DETAILS_RESET = 'CHAPTER_DETAILS_RESET';

export const CHAPTER_UPDATE_REQUEST = 'CHAPTER_UPDATE_REQUEST';
export const CHAPTER_UPDATE_SUCCESS = 'CHAPTER_UPDATE_SUCCESS';
export const CHAPTER_UPDATE_FAIL = 'CHAPTER_UPDATE_FAIL';
export const CHAPTER_UPDATE_RESET = 'CHAPTER_UPDATE_RESET';

export const CHAPTER_DELETE_REQUEST = 'CHAPTER_DELETE_REQUEST';
export const CHAPTER_DELETE_SUCCESS = 'CHAPTER_DELETE_SUCCESS';
export const CHAPTER_DELETE_FAIL = 'CHAPTER_DELETE_FAIL';
