export const EVENT_NEW_REQUEST = 'EVENT_NEW_REQUEST';
export const EVENT_NEW_SUCCESS = 'EVENT_NEW_SUCCESS';
export const EVENT_NEW_FAIL = 'EVENT_NEW_FAIL';
export const EVENT_NEW_RESET = 'EVENT_NEW_RESET';

export const EVENT_ALL_REQUEST = 'EVENT_ALL_REQUEST';
export const EVENT_ALL_SUCCESS = 'EVENT_ALL_SUCCESS';
export const EVENT_ALL_FAIL = 'EVENT_ALL_FAIL';

export const EVENT_BY_ID_REQUEST = 'EVENT_BY_ID_REQUEST';
export const EVENT_BY_ID_SUCCESS = 'EVENT_BY_ID_SUCCESS';
export const EVENT_BY_ID_FAIL = 'EVENT_BY_ID_FAIL';
export const EVENT_BY_ID_RESET = 'EVENT_BY_ID_RESET';

export const EVENT_UPDATE_BY_ID_REQUEST = 'EVENT_UPDATE_BY_ID_REQUEST';
export const EVENT_UPDATE_BY_ID_SUCCESS = 'EVENT_UPDATE_BY_ID_SUCCESS';
export const EVENT_UPDATE_BY_ID_FAIL = 'EVENT_UPDATE_BY_ID_FAIL';
export const EVENT_UPDATE_BY_ID_RESET = 'EVENT_UPDATE_BY_ID_RESET';

export const EVENT_DELETE_REQUEST = 'EVENT_DELETE_REQUEST';
export const EVENT_DELETE_SUCCESS = 'EVENT_DELETE_SUCCESS';
export const EVENT_DELETE_FAIL = 'EVENT_DELETE_FAIL';

//////////////////EVENT CONTACT/////////////////////
export const EVENT_CONTACT_NEW_REQUEST = 'EVENT_CONTACT_NEW_REQUEST';
export const EVENT_CONTACT_NEW_SUCCESS = 'EVENT_CONTACT_NEW_SUCCESS';
export const EVENT_CONTACT_NEW_FAIL = 'EVENT_CONTACT_NEW_FAIL';
export const EVENT_CONTACT_NEW_RESET = 'EVENT_CONTACT_NEW_RESET';

export const EVENT_CONTACT_ALL_REQUEST = 'EVENT_CONTACT_ALL_REQUEST';
export const EVENT_CONTACT_ALL_SUCCESS = 'EVENT_CONTACT_ALL_SUCCESS';
export const EVENT_CONTACT_ALL_FAIL = 'EVENT_CONTACT_ALL_FAIL';

export const EVENT_CONTACT_BY_ID_REQUEST = 'EVENT_CONTACT_BY_ID_REQUEST';
export const EVENT_CONTACT_BY_ID_SUCCESS = 'EVENT_CONTACT_BY_ID_SUCCESS';
export const EVENT_CONTACT_BY_ID_FAIL = 'EVENT_CONTACT_BY_ID_FAIL';
export const EVENT_CONTACT_BY_ID_RESET = 'EVENT_CONTACT_BY_ID_RESET';

export const EVENT_CONTACT_UPDATE_BY_ID_REQUEST =
  'EVENT_CONTACT_UPDATE_BY_ID_REQUEST';
export const EVENT_CONTACT_UPDATE_BY_ID_SUCCESS =
  'EVENT_CONTACT_UPDATE_BY_ID_SUCCESS';
export const EVENT_CONTACT_UPDATE_BY_ID_FAIL =
  'EVENT_CONTACT_UPDATE_BY_ID_FAIL';
export const EVENT_CONTACT_UPDATE_BY_ID_RESET =
  'EVENT_CONTACT_UPDATE_BY_ID_RESET';

export const EVENT_CONTACT_DELETE_REQUEST = 'EVENT_CONTACT_DELETE_REQUEST';
export const EVENT_CONTACT_DELETE_SUCCESS = 'EVENT_CONTACT_DELETE_SUCCESS';
export const EVENT_CONTACT_DELETE_FAIL = 'EVENT_CONTACT_DELETE_FAIL';

// ///////////////EVENT PUBLISH///////////////////
export const EVENT_PUBLISH_REQUEST = 'EVENT_PUBLISH_REQUEST';
export const EVENT_PUBLISH_SUCCESS = 'EVENT_PUBLISH_SUCCESS';
export const EVENT_PUBLISH_FAIL = 'EVENT_PUBLISH_FAIL';
export const EVENT_PUBLISH_RESET = 'EVENT_PUBLISH_RESET';

// ///////////////EVENT PUBLISH///////////////////
export const EVENT_UNPUBLISH_REQUEST = 'EVENT_UNPUBLISH_REQUEST';
export const EVENT_UNPUBLISH_SUCCESS = 'EVENT_UNPUBLISH_SUCCESS';
export const EVENT_UNPUBLISH_FAIL = 'EVENT_UNPUBLISH_FAIL';
export const EVENT_UNPUBLISH_RESET = 'EVENT_UNPUBLISH_RESET';

///////////////////EVENT REGISTRATION/////////////////////////////
export const EVENT_REGISTER_REQUEST = 'EVENT_REGISTER_REQUEST';
export const EVENT_REGISTER_SUCCESS = 'EVENT_REGISTER_SUCCESS';
export const EVENT_REGISTER_FAIL = 'EVENT_REGISTER_FAIL';
export const EVENT_REGISTER_RESET = 'EVENT_REGISTER_RESET';
